# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CI/CD pipeline for HelloSpring

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'


    - name: Build with Maven
      run: mvn clean install


    - name: uploading build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target/*.jar 


    - name: Checkout Artifacts branchgit
      run: |
        git config user.name "jayant0146"
        git config user.email "sahujayant046@gmail.com"
        git checkout -b artefacts-store
        git status

    - name: Add and Commit Artifacts
      run: |
        git checkout artefacts-store
        if [ -d "$GITHUB_WORKSPACE/target/" ] && [ "$(ls -A $GITHUB_WORKSPACE/target/*.jar)" ]; then
          cp -r $GITHUB_WORKSPACE/target/*.jar .
          git add .
          git commit -m "Upload artifacts"
          git push https://${{ secrets.ACTIONS_PAT }}@github.com/jayant0146/hello-spring-master.git artefacts-store
        else
          echo "No artifacts found to upload."
        fi

  downloading-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Artifacts Branch
      uses: actions/checkout@v4
      with:
        ref: artefacts-store
 
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
        path: target/*.jar
    - name: Display structure of downloaded files
      run: ls -R  
  
