# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CI/CD pipeline for HelloSpring

on:
  push:
    branches:
      -master
  pull_request:
    branches:
      -master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Test Cases
      run: mvn test
