# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CI/CD pipeline for HelloSpring

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v4

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Test Cases
      run: mvn test
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/libs/

    - name: Checkout Artifacts branch
      run: |
        git config user.name "jayant0146"
        git config user.email "sahujayant046@gmail.com"
        git checkout --orphan artefacts-store
        git reset --hard
        git commit --allow-empty -m "Initialize branch"
        git push origin artefacts-store

    - name: Add and Commit Artifacts
      run: |
        git checkout artefacts-store
        cp -r $GITHUB_WORKSPACE/build/libs/* .
        git add .
        git commit -m "Upload artifacts"
        git push origin artefacts-store


