# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CI/CD pipeline for HelloSpring

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'


    - name: Build with Maven
      run: mvn clean install
    - name: Run Test Cases
      run: mvn clean test -X

    - name: Checkout Artifacts branchgit
      run: |
        git config user.name "jayant0146"
        git config user.email "sahujayant046@gmail.com"
        git checkout -b artefacts-store
        git add .
        git commit -m "Initialize branch"
        git push origin artefacts-store